# Generated by Django 5.2.6 on 2025-10-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatlog', '0002_userknowledgebase_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userknowledgebase',
            name='user',
        ),
        migrations.AddField(
            model_name='userknowledgebase',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
