# Generated by Django 5.2.6 on 2025-11-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatlog', '0004_uploadedpdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedpdf',
            name='file_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
