# Generated by Django 5.2.6 on 2025-11-18 12:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatlog', '0005_uploadedpdf_file_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, default=uuid.uuid4, max_length=255, unique=True)),
                ('title', models.CharField(default='New Chat', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('user_knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='chatlog.userknowledgebase')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, default=uuid.uuid4, max_length=255, unique=True)),
                ('role', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatlog.chatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user_knowledge_base', '-updated_at'], name='chatlog_cha_user_kn_238d18_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'created_at'], name='chatlog_cha_session_146180_idx'),
        ),
    ]
