# Generated by Django 5.2.6 on 2025-12-12 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatlog', '0006_chatsession_chatmessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('emoji', models.CharField(default='📄', max_length=10)),
                ('summary', models.TextField()),
                ('key_topics', models.JSONField(default=list)),
                ('suggested_questions', models.JSONField(default=list)),
                ('source_count', models.IntegerField(default=0)),
                ('source_filenames', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_summaries', to='chatlog.userknowledgebase')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('source_type', models.CharField(max_length=50)),
                ('source_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_notes', to='chatlog.userknowledgebase')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('thumbs_up', 'Thumbs Up'), ('thumbs_down', 'Thumbs Down'), ('save_note', 'Saved to Notes'), ('copy', 'Copied')], max_length=20)),
                ('content_type', models.CharField(choices=[('summary', 'Document Summary'), ('chat_response', 'Chat Response')], max_length=20)),
                ('content_id', models.CharField(blank=True, max_length=255, null=True)),
                ('content_preview', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='chatlog.userknowledgebase')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
