# Generated by Django 5.2.6 on 2025-12-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatlog', '0007_documentsummary_savednote_userfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedpdf',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedpdf',
            name='status',
            field=models.CharField(choices=[('uploading', 'Uploading'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploading', max_length=20),
        ),
    ]
