# Generated by Django 5.2.6 on 2025-12-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatlog', '0008_uploadedpdf_error_message_uploadedpdf_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('msha', 'MSHA Regulations'), ('osha', 'OSHA Standards'), ('state', 'State Regulations'), ('best_practice', 'Best Practices'), ('training', 'Training Materials')], max_length=50)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('regulation_code', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('file_size', models.BigIntegerField(default=0)),
                ('chunks_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploading', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Foundation Document',
                'verbose_name_plural': 'Foundation Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
