FROM ankane/pgvector:v0.4.1

#
# COPY ./compose/production/postgres/init.sh /docker-entrypoint-initdb.d
# RUN chmod +x /docker-entrypoint-initdb.d/init.sh
# RUN /docker-entrypoint-initdb.d/init.sh
# # ENTRYPOINT "/docker-entrypoint-initdb.d/install-extensions.sql"